spring:
  application:
    name: admin-server
server:
  port: 8080

eureka:
  client:
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://saftop:saftop9854@20.0.0.48:8700/eureka/
  instance:
    prefer-ip-address: true
