server:
  port: 8081
spring:
  application:
    name: admin-cache
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://20.0.0.252:3306/test1?characterEncodeing=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: saftop9854@
    druid:
      web-stat-filter:
        enabled: true
      filter:
        stat:
          enabled: true
      stat-view-servlet:
        enabled: true
        login-username: saftop
        login-password: saftop9854
        allow:
      initial-size: 1
      max-active: 20
      min-idle: 1
      test-on-borrow: true
  data:
    redis:
      database: 5
      host: 20.0.0.252
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 1
      password: saftop9854
      port: 6379
      timeout:
  cache:
    type: redis
    redis:
      time-to-live: 20000
      cache-null-values: true
logging:
  level:
#    root: debug
#    org:
#      example:
#        mapper: debug
#    io:
#      lettuce:
#        core:
#          RedisClient: debug
    io:
      lettuce:
        core:
          RedisChannelHandler: debug
